//Action types
export const SELECT_ORGANISATION = 'SELECT_ORGANISATION'
export const DESELECT_ORGANISATION = 'DESELECT_ORGANISATION'
export const ADD_ORGANISATION = 'ADD_ORGANISATION'
export const EDIT_ORGANISATION = 'EDIT_ORGANISATION'
export const DELETE_ORGANISATION = 'DELETE_ORGANISATION'
