// Action types
export const SELECT_ITEM = 'SELECT_ITEM'
export const DESELECT_ITEM = 'DESELECT_ITEM'
export const ADD_ITEM = 'ADD_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const UPDATE_ITEMS = 'UPDATE_ITEMS'
export const SELECT_VIEW = 'SELECT_VIEW'
export const SELECT_FILTER = 'SELECT_FILTER'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const SET_KEYWORD = 'SET_KEYWORD'
export const SET_MESSAGE = 'SET_MESSAGE'
export const HANDLE_XHR_ERROR = 'HANDLE_XHR_ERROR'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
